### ISSUE TITLE
Update Your project info with tags please

### ISSUE THREAD

**Issue by WebCrew** [alchemMX/Velux-Prime#1]
**Hi mate thx for the nice theme its awesome.**

It would be of great help if You update the project info with some "tags" like "codoforum" and "codologic" etc. That way people which are looking for Codoforum related themes and modules will find em a lot faster here at GitHub.

For example: https://github.com/WebCrew/WebCrew_codarko

Kind regards, Andy

**Comment by alchemMX** [comment]
Fixed, I totally forgot about them, my fault.

Regards,
Sebastian.
